# Copyright 2021 Canonical Ltd.
# See LICENSE file for licensing details.

# Testing tools configuration
[tool.coverage.run]
branch = true

[tool.coverage.report]
show_missing = true

# Formatting tools configuration
[tool.black]
line-length = 99
target-version = ["py38"]

# Linting tools configuration
[tool.ruff]
line-length = 99
extend-exclude = ["__pycache__", "*.egg_info"]
select = ["E", "W", "F", "C", "N", "R", "D", "I001"]
ignore = [
  "E501", # Using black creates errors with this
  "D107", # Missing docstring in __init__
  "W605", # Pyright not recognizing raw strings
  "RET504",
  "C901"
]

[tool.ruff.per-file-ignores]
# D100, D101, D102, D103: Ignore missing docstrings in tests
"tests/*" = ["D100","D101","D102","D103"]
"lib/charms/nrpe_exporter/*" = ["C901"]

[tool.ruff.pydocstyle]
convention = "google"

# Static analysis tools configuration
[tool.pyright]
extraPaths = ["lib"]
pythonVersion = "3.8"
pythonPlatfrom = "Linux"

[tool.pytest.ini_options]
minversion = "6.0"
log_cli_level = "INFO"
