{
 "title": "NRPE Metrics and Logs",
 "tags": [ "charm: cos-proxy" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "juju_model_uuid",
    "label": "Juju model uuid",
    "query": {
     "query": "label_values(up{juju_model=~\"$juju_model\"},juju_model_uuid)"
    }
   },
   { "name": "juju_model", "label": "Juju model", "query": { "query": "label_values(up,juju_model)" } },
   {
    "name": "juju_unit",
    "query": {
     "query": "label_values(up{juju_application=~\"$juju_application\"}, juju_unit)"
    }
   },
   {
    "name": "juju_application",
    "query": {
     "query": "label_values(up, juju_application)"
    }
   },
   { "name": "prometheusds", "query": "prometheus" },
   { "name": "lokids", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "NRPE Commands Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "NRPE Command Status",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "command_ok{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}",
     "legendFormat": "{{command}} ({{juju_unit}})"
    }
   ]
  },
  {
   "title": "NRPE Checks Overview",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "{juju_unit=~\"$juju_unit\", juju_application=~\"$juju_application\", juju_model=~\"$juju_model\", juju_model_uuid=~\"$juju_model_uuid\"} | json | level=\"info\" | command=~\".+\"",
     "resolution": 1
    }
   ]
  },
  {
   "title": "NRPE Command Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "command_duration{juju_application=\"nrpe\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}",
     "legendFormat": "{{command}} ({{juju_unit}})"
    }
   ]
  },
  {
   "title": "NRPE Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "scrape_duration_seconds{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}",
     "legendFormat": "{{command}} ({{juju_unit}})"
    }
   ]
  },
  {
   "title": "NRPE Critical Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "{juju_unit=~\"$juju_unit\", juju_application=~\"$juju_application\", juju_model=~\"$juju_model\", juju_model_uuid=~\"$juju_model_uuid\"} | json | level=\"info\" | command=~\".+\" | return_code!=\"0\""
    }
   ]
  },
  { "title": "NRPE Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "NRPE Logs",
   "type": "logs",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "{juju_unit=~\"$juju_unit\", juju_application=~\"$juju_application\", juju_model=~\"$juju_model\", juju_model_uuid=~\"$juju_model_uuid\"} | json | level=\"info\" | command=~\".+\""
    }
   ]
  }
 ]
}